# Broker Server服务端配置
broker.server.host=127.0.0.1
broker.server.port=6712
broker.server.socket.rcv.buf=10240
broker.server.socket.snd.buf=10240
broker.server.socket.io.threads=10
broker.server.mq.worker.threads=50
broker.server.mq.queue.size=4096

# Broker Server客户端连接配置
broker.message.sync.socket.threads=50
broker.message.sync.socket.snd.buf=10240
broker.message.sync.socket.rcv.buf=10240
broker.message.sync.socket.epoll=false


